import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Chaitanya',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: true,
    },
    {
      name: 'Gupta',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'Nike Air Zoom',
      slug: 'nike-air-zoom',
      category: 'Shoes',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,
      description: 'Comfortable running shoes',
      featured: true,
    },
    {
      name: 'Adidas Ultraboost',
      slug: 'adidas-ultraboost',
      category: 'Shoes',
      image: '/images/p2.jpg',
      price: 180,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 18,
      description: 'Premium Adidas running shoes',
      featured: true,
    },
    {
      name: 'Puma Sports Shoes',
      slug: 'puma-sports-shoes',
      category: 'Shoes',
      image: '/images/p3.jpg',
      price: 95,
      countInStock: 20,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 9,
      description: 'Durable Puma sports shoes',
    },
    {
      name: 'Reebok Classic Shoes',
      slug: 'reebok-classic-shoes',
      category: 'Shoes',
      image: '/images/p4.jpg',
      price: 110,
      countInStock: 8,
      brand: 'Reebok',
      rating: 4.2,
      numReviews: 7,
      description: 'Classic Reebok sneakers',
    },
    {
      name: 'Nike Slim Fit Shirt',
      slug: 'nike-slim-fit-shirt',
      category: 'Shirts',
      image: '/images/p5.jpg',
      price: 45,
      countInStock: 25,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 14,
      description: 'Stylish slim fit shirt',
    },
    {
      name: 'Adidas Casual Shirt',
      slug: 'adidas-casual-shirt',
      category: 'Shirts',
      image: '/images/p6.jpg',
      price: 40,
      countInStock: 30,
      brand: 'Adidas',
      rating: 4.1,
      numReviews: 11,
      description: 'Comfortable cotton shirt',
    },
    {
      name: 'Puma Training Shirt',
      slug: 'puma-training-shirt',
      category: 'Shirts',
      image: '/images/p7.jpg',
      price: 38,
      countInStock: 18,
      brand: 'Puma',
      rating: 4.2,
      numReviews: 10,
      description: 'Perfect for workouts',
    },
    {
      name: 'Nike Jogger Pants',
      slug: 'nike-jogger-pants',
      category: 'Pants',
      image: '/images/p8.jpg',
      price: 60,
      countInStock: 16,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 15,
      description: 'Comfortable jogger pants',
    },
    {
      name: 'Adidas Track Pants',
      slug: 'adidas-track-pants',
      category: 'Pants',
      image: '/images/p9.jpg',
      price: 55,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 10,
      description: 'Lightweight track pants',
    },
    {
      name: 'Puma Slim Pants',
      slug: 'puma-slim-pants',
      category: 'Pants',
      image: '/images/p10.jpg',
      price: 50,
      countInStock: 14,
      brand: 'Puma',
      rating: 4.0,
      numReviews: 6,
      description: 'Slim fit casual pants',
    },

    {
      name: 'Nike Hoodie',
      slug: 'nike-hoodie',
      category: 'Hoodies',
      image: '/images/p11.jpg',
      price: 70,
      countInStock: 9,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 13,
      description: 'Warm winter hoodie',
    },
    {
      name: 'Adidas Hoodie',
      slug: 'adidas-hoodie',
      category: 'Hoodies',
      image: '/images/p12.jpg',
      price: 65,
      countInStock: 11,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 9,
      description: 'Stylish Adidas hoodie',
    },
    {
      name: 'Puma Hoodie',
      slug: 'puma-hoodie',
      category: 'Hoodies',
      image: '/images/p13.jpg',
      price: 60,
      countInStock: 17,
      brand: 'Puma',
      rating: 4.2,
      numReviews: 8,
      description: 'Casual hoodie',
    },

    {
      name: 'Nike Cap',
      slug: 'nike-cap',
      category: 'Accessories',
      image: '/images/p14.jpg',
      price: 20,
      countInStock: 30,
      brand: 'Nike',
      rating: 4.1,
      numReviews: 5,
      description: 'Sporty cap',
    },
    {
      name: 'Adidas Cap',
      slug: 'adidas-cap',
      category: 'Accessories',
      image: '/images/p15.jpg',
      price: 18,
      countInStock: 28,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 4,
      description: 'Stylish Adidas cap',
    },

    {
      name: 'Nike Sports Bag',
      slug: 'nike-sports-bag',
      category: 'Bags',
      image: '/images/p16.jpg',
      price: 85,
      countInStock: 13,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 12,
      description: 'Large sports bag',
    },
    {
      name: 'Adidas Gym Bag',
      slug: 'adidas-gym-bag',
      category: 'Bags',
      image: '/images/p17.jpg',
      price: 75,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 9,
      description: 'Durable gym bag',
    },

    {
      name: 'Nike Shorts',
      slug: 'nike-shorts',
      category: 'Shorts',
      image: '/images/p18.jpg',
      price: 35,
      countInStock: 22,
      brand: 'Nike',
      rating: 4.3,
      numReviews: 7,
      description: 'Comfortable sports shorts',
    },
    {
      name: 'Adidas Training Shorts',
      slug: 'adidas-training-shorts',
      category: 'Shorts',
      image: '/images/p19.jpg',
      price: 32,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 6,
      description: 'Breathable training shorts',
    },

    {
      name: 'Puma Socks Pack',
      slug: 'puma-socks-pack',
      category: 'Accessories',
      image: '/images/p20.jpg',
      price: 15,
      countInStock: 40,
      brand: 'Puma',
      rating: 4.4,
      numReviews: 8,
      description: 'Pack of sports socks',
    },

    {
      name: 'Nike Training Jacket',
      slug: 'nike-training-jacket',
      category: 'Jackets',
      image: '/images/p21.jpg',
      price: 95,
      countInStock: 7,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 14,
      description: 'Lightweight training jacket',
    },
    {
      name: 'Adidas Winter Jacket',
      slug: 'adidas-winter-jacket',
      category: 'Jackets',
      image: '/images/p22.jpg',
      price: 120,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.8,
      numReviews: 16,
      description: 'Warm winter jacket',
    },

    {
      name: 'Puma Windbreaker',
      slug: 'puma-windbreaker',
      category: 'Jackets',
      image: '/images/p23.jpg',
      price: 90,
      countInStock: 6,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 9,
      description: 'Stylish windbreaker jacket',
    },

    {
      name: 'Nike Backpack',
      slug: 'nike-backpack',
      category: 'Bags',
      image: '/images/p24.jpg',
      price: 60,
      countInStock: 18,
      brand: 'Nike',
      rating: 4.6,
      numReviews: 11,
      description: 'Spacious backpack',
    },

    {
      name: 'Adidas Travel Backpack',
      slug: 'adidas-travel-backpack',
      category: 'Bags',
      image: '/images/p25.jpg',
      price: 70,
      countInStock: 14,
      brand: 'Adidas',
      rating: 4.4,
      numReviews: 10,
      description: 'Perfect travel backpack',
    },
  ],
};

export default data;